spring:
  datasource:
    url: jdbc:mysql://ars.comk6y2dtzgi.us-west-2.rds.amazonaws.com:3306/kurly
    username: root
    password: kurlyars2022!
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    consumer:
      bootstrap-servers: 3.37.151.144:9092
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 3.37.151.144:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer